### ISSUE TITLE
Command from driver.write_import_call() does not work in Neo4j 5.x

### ISSUE THREAD

**Issue by dgg32** [biocypher/biocypher#102]
The neo4j-admin executable in Neo4j 5.x is different from that of 4.x. The command "import" has been removed. So the command generated from driver.write_import_call() does not work in 5.x any more.

**Comment by supermaxiste** [comment]
From the [tutorial page](https://biocypher.org/tutorial.html#importing-data-into-neo4j):

![image](https://user-images.githubusercontent.com/7497928/218041738-44786b85-3767-4b8a-9278-ea6b27a314b0.png)

**Comment by slobentanzer** [comment]
Thanks, @dgg32 and @supermaxiste. It is on the roadmap, it's issue #83.

**Comment by nilskre** [comment]
Starting with BioCypher `v0.5.41` Neo4j v5 is now supported.
