### ISSUE TITLE
Output adapters for RDF format

### ISSUE THREAD

**Issue by supermaxiste** [biocypher/biocypher#106]
After going through the documentation I couldn't find anything related to output adapters, even though they're mentioned in your publication.

I was specifically looking for a way to convert current CSV outputs into RDF format, but couldn't find anything. Is there any implementation available yet? If not, are there any guidelines on how to implement these output adapters? 
I'm asking since the input adapters have a blank project template and there are some basic guidelines in your documentation. There are also examples that can be used as a reference, but nothing regarding output.

I find the BioCypher initiative very interesting and ambitious, so if I could contribute to it with this let me know :)

**Comment by slobentanzer** [comment]
Hi @supermaxiste,
yes, we want to broaden the scope of output adapters, but they are not implemented yet. We have partners that are also interested in RDF output, so we are planning to do that soon, but so far I have been waiting for them. However, if you're interested and motivated, I would be very happy to include you among the contributors. We are currently doing a pretty extensive refactor on the dev branch, so I think getting in contact would be best in this case. We can also derive guidelines for output adapter creation as we go along.

Do you want to write me an email at sebastian.lobentanzer@uni-heidelberg.de, to talk about specific plans?

**Comment by slobentanzer** [comment]
new PR at #338
