### ISSUE TITLE
GitHub action to test Windows/Linux/Mac operability

### ISSUE THREAD

**Issue by slobentanzer** [biocypher/biocypher#195]

**Comment by slobentanzer** [comment]
> Can the tests also be run in offline mode without a running neo4j/postgres instance?

The testing setup should automatically skip tests if the databases are not detected.

> Would it be an option to not test on Windows?

If we can have a limited testing setup that does not run some subset of tests, I think that would be a sufficient start. Maybe someone else more proficient in Windows can fix it at a later time. I don't see it as super high priority, and I would close this issue also with partial coverage in windows, which we can just declare somewhere. I'd still compute coverage from the "main" (linux) test environment.

**Comment by nilskre** [comment]
Super, thanks. Then we can do it exactly like this and start testing Windows without the Neo4j and Postgres Docker Setup and later on, somebody with better Windows knowledge can improve it.

Final state:
The CI/CD pipeline is adapted and works now on all platforms. For Linux and Macos with Neo4j and Postgres Setup. For Windows without Neo4j and Postgres Setup (this is mentioned in a comment in the cicd.yaml).

The test on all platforms and for all supported Python versions is only run on pull requests. For every other commit the tests and code quality check is only run on Linux with one specified Python version. 
Advantages of this config:
- Fast feedback within the development cycle
- Ensured, that only changes, which are compatible with all platforms are merged into main.

**Comment by slobentanzer** [comment]
Awesome :)
