### ISSUE TITLE
Documentation: jupyter notebook and pandas output

### ISSUE THREAD

**Issue by slobentanzer** [biocypher/biocypher#197]
Essentially, transform the current tutorial into jpynb format and utilising the pandas output to bring it closer to analysis workflows.

**Comment by dbdimitrov** [comment]
Pending merge to support Pandas dataframes 

https://github.com/biocypher/biocypher/blob/5dd24d9f4e29fc5b9b9cc67ce0fe4c443dc18432/biocypher/_pandas.py#L4

https://github.com/biocypher/biocypher/blob/5dd24d9f4e29fc5b9b9cc67ce0fe4c443dc18432/biocypher/_core.py#L276

**Comment by dbdimitrov** [comment]
Would be a good place to also link to:
https://scverse.org/scirpy/latest/tutorials/tutorial_3k_tcr.html#Query-epitope-databases

potentially interesting for @ChangLu92
