### ISSUE TITLE
Is there a tutorial on how to extract gene metabolite relationship with this tool?

### ISSUE THREAD

**Issue by wanglu2014** [biocypher/biocypher#216]
This tool have a tutorial with a lof of script. However, how to do some specific and practical task, such as extracting disease-disease relationship?

**Comment by slobentanzer** [comment]
Hi @wanglu2014,
thanks for your question. The common procedure would be to first look into the currently available adapters and pipelines, which are collected here: https://github.com/orgs/biocypher/projects/3. If you can find a pipeline that is close to what you want to do, you can get the corresponding repo and try to run it for yourself. If there is no pipeline, but an adapter that looks useful, you can get started on your own pipeline by using that particular adapter as an import into the [template repository](https://github.com/biocypher/project-template) and see how that works for you. Finally, if there is no pipeline or adapter that looks good for your purpose, you can either start on your own adapter (following the [tutorial](https://biocypher.org/tutorial-adapter.html)) based on an adequate resource, or get in contact on the [Zulip chat](https://biocypher.zulipchat.com) to ask informally whether someone has already done something like that, or is actively working on it.

Generally, you can ask about any of these cases on Zulip. For diseases, for instance, the Open Targets pipeline or the CROssBAR v2 pipeline may be of interest to you.

**Comment by slobentanzer** [comment]
Closed due to duplicate (asked again in the Zulip, https://biocypher.zulipchat.com/#narrow/stream/371278-help/topic/How.20to.20extract.20the.20relationships.20between.20different.20diseases.3F).
