### ISSUE TITLE
Add CITATION.cff

### ISSUE THREAD

**Issue by slobentanzer** [biocypher/biocypher#246]
https://citation-file-format.github.io

**Comment by nilskre** [comment]
First draft of CITATION.cff: [https://github.com/nilskre/biocypher/blob/PyOpenSci_review/CITATION.cff](https://github.com/nilskre/biocypher/blob/PyOpenSci_review/CITATION.cff).
Questions:
- Is it alright like this?
- Should this file also include all the authors of the paper (at the moment it contains Sebastian and Julio in the author field)?
