### ISSUE TITLE
Correct tutorial imports

### ISSUE THREAD

**Issue by slobentanzer** [biocypher/biocypher#251]
review comment:

The basic tutorial suggests to run poetry run python tutorial/01__basic_import.py. This cannot currently work as the line `from tutorial.data_generator import Protein` will fail. The tutorial directory will require an __init__.py module and it would need to be on the PYTHONPATH. Alternatively, users could be required to change the working directory into tutorial and the scripts are adjusted to import the data_generator directly.

**Comment by slobentanzer** [comment]
For me this similarly works, which is no surprise, since I am the one who wrote it. ;)

This was reported by @Midnighter; would you be able to comment directly?

**Comment by Midnighter** [comment]
It might be that I did a simple `python tutorial/01__basic_import.py` rather than a `poetry run`. Can't fully remember. I'll try to check tomorrow.

**Comment by slobentanzer** [comment]
@Midnighter did you find some time to check?

**Comment by Midnighter** [comment]
Sorry, this dropped off my radar for a while.

I can confirm that pulling the latest `main` branch, then `poetry install`, followed by `poetry run ...` works as expected.

**Comment by slobentanzer** [comment]
Great, thanks for the feedback! Closing.
