### ISSUE TITLE
Execute code in documentation to identify outdated function calls

### ISSUE THREAD

**Issue by slobentanzer** [biocypher/biocypher#252]
The basic tutorial mentions a method `bc.log_missing_bl_types()     # show input` unaccounted for in the schema. This method no longer exists on the BioCypher class. We recommend to execute code in documentation in order to discover such problems quickly.

**Comment by nilskre** [comment]
Used doctest to fix this. 
[Official docs](https://sphinx-tutorial.readthedocs.io/step-3/#testing-your-code)
[Helpful link for the Python syntax](https://mitiq.readthedocs.io/en/stable/contributing_docs.html#run-the-code-with-doctest)

To run all tests within the documentation: `poetry run make doctest`  
This will be integrated into the CI/CD pipeline when working on #259
