### ISSUE TITLE
Replace single-letter variables everywhere (particularly tests)

### ISSUE THREAD

**Issue by slobentanzer** [biocypher/biocypher#254]
review comment: While the code formatting is fine style-wise, in particular the tests make ample use of single letter variables. This is against the pep8 guidelines and current best practices in general. We recommend using descriptive variable names everywhere.

**Comment by nilskre** [comment]
I have checked using the linter flake8, that there are no single-letter variables anymore.
We could think about adding a linter (like flake8) as pre-commit hook, to ensure, that all PEP 8 rules, which are not considered automatically by black are not ignored (like single-letter variables). 
What do you think?

**Comment by slobentanzer** [comment]
may be a bit overkill. i was thinking more to go through the couple single letter variables we do use and just replace them by more meaningful names, which should not take too long. we had flake8 some time ago, but i felt it cluttered the pre-commit and i prefer to use black formatting and not much else. it's a style choice though, so if it brings a lot of benefit, i may reconsider.
