### ISSUE TITLE
Auto-publish to PyPI

### ISSUE THREAD

**Issue by slobentanzer** [biocypher/biocypher#259]
review comment: You could publish the package to PyPI via a workflow as well. See [our taxpasta workflow](https://github.com/taxprofiler/taxpasta/blob/dev/.github/workflows/main.yml) for an example of how to do so.

**Comment by nilskre** [comment]
Before adding this feature it makes sense to review the whole CI/CD architecture and specify what the targeted CI/CD architecture is. Therefore here is a proposal for a branching model with CI/CD (based on Gitflow and Trunk-based workflow)

Branches:
- main: contains always the code of the currently released version
- dev: contains the current development state
- feature branches: development of new features
Feature branches are merged frequently into dev and by merging the dev branch into the main branch a new release is created.

On every pushed commit:
- run tests
- ensure code quality

Create new release:
- increase version with bumpversion and commit and push on dev
- create PR to merge dev into main
On every commit to the main branch -> create a new release (triggers CI/CD):
- run tests
- update test coverage
- check code quality
- create release
- publish to PyPi
- update docs

Changes compared to the current state (ToDos):
- Branching model with main, dev and feature branches (dev branch exists in the repo, but is not actively used at the moment)
- add code quality check
- run tests and code quality CI pipeline for every commit (currently only executed for pushes on the main branch)
- create release as part of the CI/CD pipeline

Feedback for this proposal is welcome. If this proposal is alright like this, I can work on a PR for this.

**Comment by slobentanzer** [comment]
Great work making a plan, and I agree that we need to set a target.

My main comment is that I am not a fan of long-running dev branches. The dev branch in the current repo is a good example of why I am not a fan; it contains a lot of work that currently goes unused because it was all written in one go and without tests and failing existing tests. I keep it around for reference and to maybe cherry-pick some of this work, but I haven't gotten around to it. In addition, there were other, parallel developments on other features that made some of these changes redundant or conflicting. As such, I currently work using feature branches exclusively.

There may be a good reason for having a "main `dev` branch", but as far as I understand, this is a philosophical question to some extent. What would be the benefits of having a dev branch? Would we do "pre-releases"? Could we also do the rest of your proposal without the `dev` branch?

**Comment by nilskre** [comment]
I would have not expected an answer this week (:

Yes indeed, this is a philosophical question with pros and cons for both. Without an extra dev branch everything is much simpler and there is not that much overhead.

The proposal is easily adaptable to also work without a dev branch: The only needed adaption is, that a release is created by setting a tag on the main branch (and not by merging). This is automatically done by bumpversion. The CI/CD release pipeline can then be triggered by new tags on the main branch.

**Comment by slobentanzer** [comment]
I needed to kill some time. :) will be (really) off from tomorrow on.

That sounds good, and is in principle what I currently do manually as well (with the tags). All it takes in addition for (manually) publishing to PyPI is running `poetry build` and `poetry publish`.

**Comment by nilskre** [comment]
Alright (: 
Great. Now with the targeted CI/CD pipeline in mind, this is the next Issue to be worked on.

**Comment by nilskre** [comment]
First CI/CD improvements are implemented:
- [Tests and code quality](https://github.com/nilskre/biocypher/blob/PyOpenSci_review/.github/workflows/ci_cd.yaml): Runs on every commit and runs tests  and checks the code quality
- [Release](https://github.com/nilskre/biocypher/blob/PyOpenSci_review/.github/workflows/release.yaml): Build part works, Deploy part not yet

**Comment by slobentanzer** [comment]
Setting up the github secrets for the deployment can be tricky, we can look at that next week together.

**Comment by slobentanzer** [comment]
I have set up test.pypi.org with a similar trusted publisher (the env for publishing is called `release`). We can test the workflow there.

![Screenshot 2023-09-25 at 16 34 18](https://github.com/biocypher/biocypher/assets/13223629/85e40337-c58f-4ac8-9170-505bf6c23fc6)

**Comment by slobentanzer** [comment]
On second thought, we should maybe not use the same env for the testing. I will call the environment for the test.pypi.org `staging`. This way we don't run the risk of accidentally publishing to the real PyPI (hopefully).

**Comment by nilskre** [comment]
Yes, this is a nice solution to separate the development of the autopublishing functionality from the final autopublishing workflow. 

The publish.yaml workflow is currently adapted to publish to staging (on a tag), then we can merge this into the pyopensci branch and test it there? If this turns out to be successful, we can configure this also for the release environment.

**Comment by slobentanzer** [comment]
Just writing down here the current steps that we want to partly automate:

## Bump version and update GitHub
```
bumpversion (e.g. patch)
git push
git push --tags
```

## Publish to PyPI
```
poetry build
poetry publish
```

## Create a release on Github
Manual steps:
- go to releases
- create new release (button)
- select tag that was just created (dropdown)
- automatically generate release notes (button)
- confirm release and set as latest (button)

**Comment by nilskre** [comment]
Nice overview.

Here I add the current state of automation:
- Publish to PyPI: Already automated (but not yet tested)
- Create a release on Github: Now also automated in [Commit](https://github.com/nilskre/biocypher/commit/78eeb19086276e437b8c3804b556078a7cd5a225) as part of the next [PR](https://github.com/biocypher/biocypher/pull/274) (but also not yet tested)

I am not able to test it alone, because I cannot push any tags to the original repo. Maybe we can test it together later today?

**Comment by slobentanzer** [comment]
Yeah, we can do that.
