### ISSUE TITLE
Document postgres better

### ISSUE THREAD

**Issue by slobentanzer** [biocypher/biocypher#260]
review comment: Running the tests on postgres requires not only a running database, but also the psql command line tool. I did not see this in the documentation. In general, the section https://biocypher.org/installation.html#for-developers has detailed instructions for neo4j, but not for postgres.

**Comment by nilskre** [comment]
Would it be an option to explain how to run the Docker container with Postgres (then we could reuse the command from the CICD pipeline).
Or should we describe how to install (Neo4j) Postgres/psql as native dependencies on the local machine?

**Comment by slobentanzer** [comment]
I need to write some more high-level docs anyways about docker workflows, deployment, resource management, etc. Just need to find some time. We can also meet maybe next week to talk about more advanced things to do. Would actually be nice to get your opinion on high level docs and how to make them more usable and efficient.

**Comment by nilskre** [comment]
Alright, thanks.

Yes, sounds like a great plan. As a next step, I will probably read through the docs and create a small test KG to further familiarize myself with BioCypher. I think after this I am ready and well prepared to have a discussion about this (:
