### ISSUE TITLE
Ontology: Finding root label fails

### ISSUE THREAD

**Issue by nilskre** [biocypher/biocypher#278]
This issue came up while trying to setup a BioCypher KG with Snomed CT as head ontology (BioCypher v0.5.25). The process fails with the error `ValueError: Could not find root node with label SNOMED CT Concept (SNOMED RT+CTV3)`, but the root node is present in the owl file.

Part of `biocypher_config.yaml`:
```
  head_ontology:
    url: ./my-test-kg/config/snomed-ct.owl
    root_node: SNOMED CT Concept (SNOMED RT+CTV3)
``` 

Part of snomed-ct.owl:
```
    <!-- http://snomed.info/id/138875005 -->

    <owl:Class rdf:about="http://snomed.info/id/138875005">
        <rdfs:label xml:lang="en">SNOMED CT Concept (SNOMED RT+CTV3)</rdfs:label>
        <skos:altLabel xml:lang="en">SNOMED CT has been created by combining SNOMED RT and a computer-based nomenclature and classification known as Read Codes Version 3, which was created on behalf of the U.K. Department of Health.</skos:altLabel>
        <skos:altLabel xml:lang="en">SNOMED Clinical Terms version: 20220831 [R] (August 2022 Release)</skos:altLabel>
        <skos:altLabel xml:lang="en">© 2002-2022 International Health Terminology Standards Development Organisation (IHTSDO). All rights reserved. SNOMED CT®, was originally created by The College of American Pathologists. &quot;SNOMED&quot; and &quot;SNOMED CT&quot; are registered trademarks of the IHTSDO.</skos:altLabel>
        <skos:prefLabel xml:lang="en">SNOMED CT Concept</skos:prefLabel>
    </owl:Class>
    
``` 

After some debugging, I found the line that caused the error. When changing `if o.eq(root_label):` to `str(o) == root_label:`(in [this line](https://github.com/biocypher/biocypher/blob/main/biocypher/_ontology.py#L102)), the root node is found and set without any problems. When using `if o.eq(root_label):` the root node is not found, because of different types in the comparison.
Would it be an option to change this? 

Thanks in advance!

**Comment by slobentanzer** [comment]
I remember that I had to work on that for a while, though I am not sure it is still an issue. I am fairly sure I would have tried string comparison first and for some reason then needed to do what is currently in place. Maybe other ontologies do not give you the label as str. However, if all tests pass after you change to string comparison, I don't see why we can't change it. Maybe this is an opportunity to extend the test cases of ontologies a little, we can have a look.

**Comment by nilskre** [comment]
Alright, thanks. 
Sounds like a plan. Now that the pyopensci issues are almost done: Would it be ok, if I continue with working on this issue?

**Comment by slobentanzer** [comment]
Sure, should not take too long. (If it does, let me know.. ;) )
