### ISSUE TITLE
Brackets in ontology names result in improper Neo4j file names

### ISSUE THREAD

**Issue by nilskre** [biocypher/biocypher#306]
When names in the underlying ontology contain brackets, the generated files for the Neo4j import are not proper.

Example:
- Name in the Snomed CT ontology: `Patient (person)`
- When writing the files for the Neo4j import, BioCypher transforms this name to CamelCase (results in: `Patient (person)`).
- The generated import statement `bin/neo4j-admin import --database=neo4j --delimiter="\t" --array-delimiter="|" --quote="'" --force=true --skip-bad-relationships=true --skip-duplicate-nodes=true --nodes="/biocypher-out/20240115145536/Patient (person)-header.csv,/biocypher-out/20240115145536/Patient (person)-part.*"` fails with `java.lang.IllegalArgumentException`. [Neo4j can not handle whitespaces in filenames](https://neo4j.com/developer/kb/space-in-import-filename-for-load-csv/).

After removing the whitespace and the brackets from the file names and the import statement everything works as expected.

Is there any advice on how to handle this?
I would suggest to check for not supported characters (such as brackets) and remove them before writing the files (probably in  [name_sentence_to_pascal](https://github.com/biocypher/biocypher/blob/main/biocypher/_translate.py#L470) or somewhere in [write](https://github.com/biocypher/biocypher/blob/main/biocypher/_write.py) .

**Comment by slobentanzer** [comment]
It would probably be wise to handle it at the appropriate time, i.e., do we only need to adjust the file names, or does this also affect the Labels of the nodes? While you can use spaces in Neo4j node labels, it may be better not to, because then you need to escape the labels. There is a similar problem with dots in the name; if we use the dot syntax for denoting parent-child relationships in the ontology, the label needs to be escaped (as happens for instance in the implicit inheritance case).

The pythonic way would be to just replace all instances of the characters in question with a suitable character (or remove). I think underscores could be a feasible replacement, or in some cases we can just remove them.

I don't know why whitespaces would be a problem, shouldn't the PascalCase function remove all of those?

**Comment by nilskre** [comment]
Yes, this also affects the labels of the nodes.
In the example the label is `'Patient (person)|Person (person)|PersonInTheHealthcareEnvironment (person)|SnomedCtConcept (snomedRt+ctv3)|SocialContext (socialConcept)'`.

In the example, the whitespace are removed, except for the whitespace in front of the bracket (so this is an issue with brackets and not with whitespaces).

I will create a PR to remove all instances of the characters in question with a suitable character.
Aimed goal would be labels like:
- `Patient (person)`-> `PatientPerson`
- `'Patient (person)|Person (person)|PersonInTheHealthcareEnvironment (person)|SnomedCtConcept (snomedRt+ctv3)|SocialContext (socialConcept)'` -> `'PatientPerson|PersonPerson|PersonInTheHealthcareEnvironmentPerson|SnomedCtConceptSnomedRt+ctv3|SocialContextSocialConcept'`

**Comment by slobentanzer** [comment]
Maybe a side note, but why do we need the (person) in the first place? This seems to embody the ontology hierarchy, which is unnecessary if we encode this ourselves on the nodes. The (patient) only carries redundant information in this example. Can we instead just remove brackets content, or does this lead to ambiguities in the ontology graph?

**Comment by nilskre** [comment]
> Maybe a side note, but why do we need the (person) in the first place? This seems to embody the ontology hierarchy, which is unnecessary if we encode this ourselves on the nodes. The (patient) only carries redundant information in this example. Can we instead just remove brackets content, or does this lead to ambiguities in the ontology graph?

Yes, true. In this case, it could safely be removed without any information loss. Thus the preferred solution would be to just remove the brackets and their content. Is this also the general solution we should implement in BioCypher or does this conflict with other possible use cases?

**Comment by slobentanzer** [comment]
I would suggest to at least run a test on the current ontology (i.e., look at all the labels, remove the brackets, and determine if that leads to duplicates, meaning ambiguities). If no duplications happen, it should be fine at least for now. Maybe should be noted in the docs if we decide to remove the bracketed contents.

**Comment by nilskre** [comment]
> I would suggest to at least run a test on the current ontology (i.e., look at all the labels, remove the brackets, and determine if that leads to duplicates, meaning ambiguities). If no duplications happen, it should be fine at least for now. Maybe should be noted in the docs if we decide to remove the bracketed contents.

Just checked it for the Snomed CT ontology. 
There are 388199 Snomed CT concepts in total:
- 386594 of them are unique
- 1605 of them are duplicates. E.g. `Abrasion`could be [Abrasion (morphologic abnormality)](https://browser.ihtsdotools.org/?perspective=full&conceptId1=400061001&edition=MAIN&release=&languages=en) or [Abrasion (disorder)](https://browser.ihtsdotools.org/?perspective=full&conceptId1=399963005&edition=MAIN&release=&languages=en).

-> The content in the brackets needs to be kept. 
=> Thus I would propose a solution where in the conversion process to Neo4j PascalCaseNames in BioCypher the input string is checked for compliance with the [Neo4j naming rules](https://neo4j.com/docs/cypher-manual/current/syntax/naming/). In case the input string contains not supported characters, these characters are removed and a warning is raised to inform the user.
Would that be a viable solution?

**Comment by slobentanzer** [comment]
Yes, I suppose there is no systematic way of keeping or removing all of them then...

Which is a pity, because `PatientPerson` is much less readable than `Patient` and may be confusing. Can we work with aliases/synonyms? (As we employ for example in the schema config `synonym_for` field.) The `official` name could be the complete one, but the synonym would be the more readable?

**Comment by nilskre** [comment]
> Which is a pity, because `PatientPerson` is much less readable than `Patient` and may be confusing. Can we work with aliases/synonyms? (As we employ for example in the schema config `synonym_for` field.) The `official` name could be the complete one, but the synonym would be the more readable?

That is a good idea. Thanks! I will have a look at it.
