### ISSUE TITLE
bin/neo4j-admin import not working in latest DBMS 5.15

### ISSUE THREAD

**Issue by JPonsa** [biocypher/biocypher#315]
the command reported in neo4j-admin-import-call.sh (generated using BioCypher.write_import_call()) not working in the latest DBMS version 5.15. It display message  "Did you mean: neo4j-admin database import or neo4j-admin server report or neo4j-admin dbms set-operator-password?". I also tried running bin\neo4j-admin database import --database=relationships ... but doesn't work either.

the original command works if I downgrade the 4.4.20 (I haven't tried other versions)

![image](https://github.com/biocypher/biocypher/assets/28976175/f4ca38a1-ed54-4efb-b433-788b256490d5)

Also, I faced issue https://github.com/neo4j/neo4j/issues/12633 ; meaning I had to manually create an empty db with the same name (e.g. "relationships" ) from Neo4j Desktop and refresh it after running the command. Not a biocypher issue but it could be good to add it to the tutorial guide as new users may face the same issue.

**Comment by slobentanzer** [comment]
Hi @JPonsa,
thanks for the feedback. We do indeed only support v4 currently, as we state in the [docs](https://biocypher.org/neo4j.html#tutorial-neo4j). Do you need to use v5 for a specific reason? We also have a PR in the making to support v5.

Regarding the second issue, I want to make sure I understand: you did the admin import, but still need to create the database itself in Neo4j? If so, this is known and also already described in the [docs](https://biocypher.org/neo4j.html#exporting-for-the-neo4j-admin-import-feature).

**Comment by nilskre** [comment]
Starting with BioCypher `v0.5.41` Neo4j v5 is now supported.
