### ISSUE TITLE
Multiple copies of NetworkX graph in memory: problem for larger ontologies?

### ISSUE THREAD

**Issue by slobentanzer** [biocypher/biocypher#319]
https://github.com/biocypher/biocypher/blob/06389f5c96675cb19700f4abb9aee5af8e18ca52/biocypher/_ontology.py#L110

In this method, we create multiple iterations of the initial graph object; does this create an overhead? Do we need to consider removing some of the duplications?

**Comment by nilskre** [comment]
Probably yes, I will have a detailed look at this again. At the moment the process is handable even for large ontologies (but memory intensive).
