### ISSUE TITLE
Head join node not found in head ontology

### ISSUE THREAD

**Issue by clairelaudy** [biocypher/biocypher#320]
When loading two very simple Turtle ontologies made from scratch in Protégé, configuring a tail-in fails on: "ValueError: Head join node <whatever> not found in head ontology."

## Details

```
INFO -- This is BioCypher v0.5.37.
INFO -- Logging into `biocypher-log/biocypher-20240304-214431.log`.
INFO -- Loading ontologies...
INFO -- Instantiating OntologyAdapter class for ontology1.ttl.
INFO -- Instantiating OntologyAdapter class for ontology2.ttl.
Traceback (most recent call last):
  File "/home/cl/travail/code/onto/tests/main.py", line 8, in <module>
    bc.show_ontology_structure()
  File "/home/cl/travail/code/biocypher/biocypher/_core.py", line 557, in show_ontology_structure
    self._get_ontology()
  File "/home/cl/travail/code/biocypher/biocypher/_core.py", line 199, in _get_ontology
    self._ontology = Ontology(
                     ^^^^^^^^^
  File "/home/cl/travail/code/biocypher/biocypher/_ontology.py", line 402, in __init__
    self._main()
  File "/home/cl/travail/code/biocypher/biocypher/_ontology.py", line 415, in _main
    self._assert_join_node(adapter)
  File "/home/cl/travail/code/biocypher/biocypher/_ontology.py", line 467, in _assert_join_node
    raise ValueError(
ValueError: Head join node entity not found in head ontology.
```

main.py:
```python
import biocypher

bc = biocypher.BioCypher(
    biocypher_config_path = "biocypher.yaml",
    schema_config_path = "schema.yaml"
)
bc.show_ontology_structure()
```

biocypher.yaml:
```yaml
biocypher:
    debug: true
    offline: true

    head_ontology:
        url: ontology1.ttl
        root_node: Thing

    tail_ontologies:
        urref:
            url: ontology2.ttl
            head_join_node: entity
            tail_join_node: EvaluationCriterion
```

schema.yaml:
```yaml
entity:
    represented_as: node
    label_in_input: entity

Accuracy:
    represented_as: node
    label_in_input: Accuracy

user_is_accurate:
    is_a: relation
    represented_as: edge
    label_in_input: user_is_accurate
    source: User
    target: EvaluationCriterion
```

Ontologies:
[test_2ontologies.zip](https://github.com/biocypher/biocypher/files/14487006/test_2ontologies.zip)

## Configuration

- Linux Ubuntu 23.10 (mantic)
- Protégé v5.6.3
- Installed via poetry 1.6.1
- BioCypher v0.5.37
- Python 3.11.6
- poetry.lock: [poetry.lock.txt](https://github.com/biocypher/biocypher/files/14487069/poetry.lock.txt)

**Comment by slobentanzer** [comment]
Hi @clairelaudy,
thanks for the report. :)

You are testing the slightly unrealistic case of the head ontology not having a single subClassOf definition, which leads to the parsed graph having no triples, and thus to failure. If you add one subClassOf, the example works. E.g.:

```
###  http://www.semanticweb.org/u1044/ontologies/2024/2/untitled-ontology-123/entity
:entity rdf:type owl:Class ;
        rdfs:subClassOf owl:Thing ;
        rdfs:label "entity" .
```

I have added your test case as a simple unit test: 76941d37af73c274dd534eca17f218b1a7eac17d

I don't think it makes sense to have a head ontology with no subclasses, so I guess we won't need to implement this edge case. Or do you have a use case that would make this necessary?

**Comment by clairelaudy** [comment]
While playing with the tests you added (at faf5a78), I noticed that `test_simple_ontology` asks `get_ancestors("accuracy")` in lower case, while it is written with an upper case in the ontology.
If I make it uppercase everywhere but in this accessor, it works, but if I try with an uppercase in the accessor, it doesn't, a behavior that I don't understand.

See the following patch, for instance:
```diff
@@ -238,7 +238,7 @@ def ontology_mapping():
 def simple_ontology_mapping():
     m = OntologyMapping()
     m.schema = {
-        "accuracy": {},
+        "Accuracy": {},
     }
     return m
 
diff --git a/test/test_ontology.py b/test/test_ontology.py
index 5ef1744..bd4f48b 100644
--- a/test/test_ontology.py
+++ b/test/test_ontology.py
@@ -212,8 +212,8 @@ def test_reverse_labels():
 
 
 def test_simple_ontology(simple_ontology):
-    list(simple_ontology.get_ancestors("accuracy")) == [
-        "accuracy",
+    list(simple_ontology.get_ancestors("Accuracy")) == [
+        "Accuracy",
         "entity",
         "Thing",
     ]
```

As for the edge case of having no subclass on root types, this seems to be a wanted behavior of Protégé (see [1](https://protegeproject.github.io/protege/views/class-hierarchy/) [2](https://github.com/protegeproject/protege/issues/401) [3](https://github.com/protegeproject/protege/commit/9e8678b0aa73e8ec34b0e24e538f7148fa39cd39)). This looks strange in Protégé, since the class hierarchy displays the root nodes as being under owl:Thing, while the axiom SubClassOf is actually not defined.

Now, if you consider this is a bug of Protégé (but they consider it is not), it will prevent Protégé users from easily using BioCypher. The workaround of adding a subclass within Protégé is not particularly easy to come up with given the current error, but a good compromise might be to capture the problem somewhere and print a warning suggesting adding subclass-of-Thing to root nodes.

**Comment by slobentanzer** [comment]
Hi @clairelaudy,
I appreciate the feedback, but please try to keep the issue on topic, as starting several other conversations will get confusing. If you have a separate issue, please open a dedicated one. :) I will respond to the lower case issue here, but if the problem persists, please open a new issue.

> I noticed that test_simple_ontology asks get_ancestors("accuracy") in lower case

I am not sure I fully understand; are you referring to the fact that we use lower sentence case as the internal representation of the ontologies, as described in the [docs](https://biocypher.org/tutorial-ontology.html#what-is-an-ontology)? This is simply our default approach to avoid inconsistencies.

> As for the edge case of having no subclass on root types, this seems to be a wanted behavior of Protégé (see [1](https://protegeproject.github.io/protege/views/class-hierarchy/) https://github.com/protegeproject/protege/issues/401 [3](https://github.com/protegeproject/protege/commit/9e8678b0aa73e8ec34b0e24e538f7148fa39cd39)). This looks strange in Protégé, since the class hierarchy displays the root nodes as being under owl:Thing, while the axiom SubClassOf is actually not defined.

Here as well, I am not quite sure I understand what the actual problem is (I don't use Protegé). My original comment was not that you need to make your root node a `subClassOf` `Thing`, my comment was that, if you have not a single `subClassOf` in your ontology, the parsing of the ontology fails, because the list of triples is empty. In other words, your ontology has to be a tree. If you add a second class that you make `subClassOf` your root node, the issue also does not appear.

I would guess that this case (head ontology only having one node) is not practically relevant. At least I have not encountered such an ontology so far. Feel free to clarify if I misunderstand what you actually try to achieve with your minimal example.

**Comment by slobentanzer** [comment]
Hi @clairelaudy,
any updates, is the issue resolved?

**Comment by jdreo** [comment]
The pull request #328 adds some warnings related to this issue. I must note that these are a lot of potential sources of errors coming from an input that may be managed by the user.

**Comment by nilskre** [comment]
Furthermore, in #327 (not yet merged) , some more hints are added in the error messages (e.g. when the `root_node` or the `head_join_node` are not found in the ontology the error message prints the defined term and all available items from the ontology -> makes debugging easier what the source of the error is).

**Comment by clairelaudy** [comment]
> Hi @clairelaudy, any updates, is the issue resolved?

I edited the ontology so that biocypher can handle it, yes.
Thanks.
