### ISSUE TITLE
Properties of duplicate nodes

### ISSUE THREAD

**Issue by mbaric758** [biocypher/biocypher#373]
Hi, 

I'm having an issue with the handling of properties for nodes in case of having duplicate nodes with same IDs, which have different properties, or same properties with discrepant values. For example:

`nodes = [ ('NRG1', 'gene_hugo', {'property1': 'B', 'property2': 'C'}), 
('NRG1', 'gene_hugo', {'property1': 'A', 'property2': 'C', 'property3': 'D'}) ]`

Here there's two nodes in Tuple format both representing one gene. BioCypher gives out a `WARNING -- Duplicate node type gene found.` message and then keeps only the first encountered node of that ID - so here the first `NRG1` gene, and its properties, but doesn't add the properties of the duplicate node, so `{'property1': 'A', 'property3': 'D'}` are not present in the final output, and `{'property2': 'C'} `exists since it's also present in the first node encountered.

Would there be a way of merging and combining the properties of these nodes so that they are all represented in the final output? So the property dictionary for the `NRG1` node would be `{'property1': 'A, B', 'property2': 'C', 'property3': 'D'}.`

**Comment by slobentanzer** [comment]
Hi @mbaric758,
thanks for the question. This is a fundamental problem of data harmonisation, and I have struggled with finding a general solution that covers all use cases while also remaining computationally efficient. We could screen the entire dataset for all extant properties and extract them in a second step, but that would at least double computation time and probably also increase the memory footprint considerably. For this reason, I kept the default implementation minimal.

What I would usually recommend in these cases is to have a unifying adapter as a middle layer between the individual adapters and the BioCypher core. In this case, you would have one adapter that supplies properties 1 and 2, and one adapter that supplies properties 1 and 3 (for example). I would then propose to create a second-level adapter that processes information from the original adapters, making sure that all three properties are present.

I would combine this with explicit specification of all expected properties in the schema definition, i.e.
```
gene:
  represented_as: node
  ...
  properties:
    property1: str
    property2: str
    property3: str
```

Another complication that is visible from your example is that two sources may disagree; the first adapter has `property1` as `'A'`, while the second adapter supplies `'A, B'`. Another advantage then from having a secondary adapter is that you can make procedural decisions about how to treat these disagreements; you can prioritise one source over the other, merge them, use their intersection, etc.

Is this feasible in your use case?

**Comment by slobentanzer** [comment]
@mbaric758 nice, do you have a link, out of interest?

**Comment by mbaric758** [comment]
@slobentanzer we actually do it through an OntoWeaver adapter that processes the nodes before finally passing them to BioCypher with the final property values. We're currently working on implementing an additional class in OntoWeaver to automatize the process of merging node id / property values, so it's going to be on Github soon hopefully.

**Comment by slobentanzer** [comment]
Nice, let me know once it's ready. Closing this. :)
